export type Sustainability = {
    data:{
        introTitle:string,
        introDescription:string,
        introImage:string,
        introImageAlt:string,
        sectionTwoTitle:string,
        sectionTwoDescription:string,
        practices:[{
            title:string,
            description:string,
            icon:string,
            iconAlt:string
        }],
        certifications:[{
            title:string,
            description:string,
            images:string[]
        }],
        goals:{
            title:string,
            description:string,
            items:[{
                title:string,
                description:string,
                image:string,
                iconAlt:string
            }]
        },
        outroTitle:string,
        outroDescription:string
    }
}